#!/bin/bash

URL="$1"

if [[ $URL == ^http://* ]]; then
  URL="http://$URL"
fi;

while true; do
  STATUS=$( curl -w '%{http_code}' -s --output /dev/null "$URL")

  if [[ $STATUS == "404" ]]; then
    echo "The URL $URL is down :("
  else
    notify-send --urgency critical --expire-time 2000 --icon network-receive --category network.connected "The URL is UP!" "$URL"
  fi;

  sleep 10
done

