#!/bin/sh

#set -e
#set -x

# https://askubuntu.com/a/740572
terminator && ~/bin/sm && xdotool windowsize $(xdotool getactivewindow) 100% 100%

# See also:
# https://unix.stackexchange.com/a/51817/229657
